# Création de la colonne mot vedette

In [1]:
#import de librairie
import pandas as pd

In [2]:
# chemins des deux fichiers à lire 
cheminDuFichierCSV = "./../data/dictionary/Buchanan_PronChar_counts.csv" 
CheminCSV2="./../data/dictionary/1757_Buchanan-J.csv" 
# créations des dataframes pandas correspondant 
dfmapping = (pd.read_csv(cheminDuFichierCSV, delimiter=";", encoding="utf8"))
dfDicoBuch = pd.read_csv(CheminCSV2, delimiter=";", encoding="utf8")
#remplissage des valeur nulles / non valide par un vide de chaine de caractère 
dfmapping['graph']=dfmapping['graph'].fillna("")

Affichage des deux fichiers CSV que l'on vas traité.

In [3]:
dfDicoBuch

       nbSyll        pron origin warning remarques POS  lineId  pageId
0           3     aʹbăcus    NaN     NaN       NaN  n.     2.0      19
1           2      ăbăʹft    NaN     NaN       NaN  p.     3.0      19
2           3  ăbaiʹſănce     F.     NaN       NaN  n.     4.0      19
3           3    ābăʹndon     F.     NaN       NaN  v.     5.0      19
4           4  ābăʹndŏned    NaN     NaN       NaN  a.     6.0      19
...       ...         ...    ...     ...       ...  ..     ...     ...
15795       4  zōŏʹgrăphy     G.     NaN       NaN  n.    19.0     241
15796       4  zōŏʹphytès     G.     NaN       NaN  n.    20.0     241
15797       4  zōŏʹphŏric     G.     NaN       NaN  n.    21.0     241
15798       4  zōŏʹtŏmiſt     G.     NaN       NaN  n.    22.0     241
15799       3     zŏʹtĭcā     G.     NaN       NaN  n.    23.0     241

[15800 rows x 8 columns]

In [4]:
dfmapping

   char    occ graph
0     a   3207     a
1     ʹ  12725
2     b   2288     b
3     ă   4533     a
4     c   5500     c
..  ...    ...   ...
68    á      1     a
69    I      1     l
70    х      2     x
71    р      1     p
72    ï      1     i

[73 rows x 3 columns]

In [5]:
#création de la fonction Buch2Class
def buch2Class(strBuch, dfMapping):
    #création de la variable résultat
    BuchRes = ""
    listValBuch = strBuch
    # pour un mot particuler en Buch
    for valBuch in listValBuch:
        #on regarde si on trouve une correspondance dans notre table de mapping
        dfRowFinded = dfMapping[dfMapping['char']==valBuch]
        #si on en trouve bien une alors 
        if len(dfRowFinded==1):
            #on ajoute a notre mot le caractère corespondant
            BuchRes+=dfRowFinded.iloc[0]['graph']
        else:
            BuchRes+='?'
    return BuchRes

On effectue une mannipulation afin d'avoir le mot Buch traduit en un mot classique

In [6]:
%%time
dfDicoBuch['motVedette'] = dfDicoBuch.apply(lambda x: buch2Class(x['pron'], dfmapping),1)

Wall time: 1min 9s

In [7]:
dfDicoBuch

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned
...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica

In [8]:
#on enregistre notre dictionaire (sauvegarde de secours)
dfDicoBuch.to_csv("./../data/dataframe/dfDicoBuch.csv",index=False)

# Création des colonnes Sampa et Ipa

In [9]:
# récupére notre dico enregistrer précédement.  
dfDicoBuch = pd.read_csv("./../data/dataframe/dfDicoBuch.csv" , delimiter=",", encoding="utf8")

In [10]:
#on récupère un autre dictionnaire  nommé Bigi
cheminDuDicoBigi = "./../data/dataframe/BigiRichSample.csv" 
dfBigi = (pd.read_csv(cheminDuDicoBigi, delimiter=";", encoding="utf8"))

Afin de faire la création des colonnes Sampa et Ipa on utilise le fichier BigiRichSample.csv

In [11]:
dfDicoBuch

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned
...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica

In [12]:
dfBigi

              hwd                  pronSampa            ipa
0           ruled                   r\ u l d           ɹuld
1        weingart            w aI N g A r\ t        w?ŋgɑɹt
2    continuation   k @ n t I n j u eI S @ n   kəntɪnju?ʃən
3            anas                    { n @ s           ænəs
4    advisability  { d v aI z @ b I l i 4 i:  ædv?zəbɪliɾiː
..            ...                        ...            ...
995          keir                    k i: r\           kiːɹ
996   cultivating       k V l t i v eI 4 i N     kʌltiv?ɾiŋ
997   pendergrass       p E n d 3:r g r\ @ s    pɛndɜ:rgɹəs
998   gentrifying     dZ E n t r\ i f aI i N     ?ɛntɹif?iŋ
999        ladder                  l { 4 3:r         læɾɜ:r

[1000 rows x 3 columns]

In [13]:
#même principe que pour la fonction Buch2Class. 
#cet fois si on cherche basiquement si le mot ce trouve dans la colonne Sampa ou Ipa du dico de Bigi. sans chercher de caractère particulier. 
def addSampa(strBuch, dfBigi):
    BuchRes = ""
    dfRowFinded = dfBigi[dfBigi['hwd']==strBuch]
    if len(dfRowFinded==1):
        BuchRes=dfRowFinded.iloc[0]['pronSampa']
    else:
        BuchRes='?'
    return BuchRes

def addIpa(strBuch, dfBigi):
    BuchRes = ""
    dfRowFinded = dfBigi[dfBigi['hwd']==strBuch]
    if len(dfRowFinded==1):
        BuchRes=dfRowFinded.iloc[0]['ipa']
    else:
        BuchRes='?'
    return BuchRes

In [14]:
dfDicoBuch['Sampa'] = dfDicoBuch.apply(lambda x: addSampa(x['motVedette'], dfBigi),1)
dfDicoBuch['Ipa'] = dfDicoBuch.apply(lambda x: addIpa(x['motVedette'], dfBigi),1)

Wall time: 5.25 s

Après 12secondes de temps de traitement environ on trouve cet table

In [16]:
dfDicoBuch

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette,Sampa,Ipa
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus,?,?
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft,?,?
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance,?,?
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon,?,?
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned,?,?
...,...,...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography,?,?
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes,?,?
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric,?,?
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist,?,?
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica,?,?

On remarque qu'il y a beaucoup de point d'interogations et on effectue une inspection de la table.

In [17]:
dfDicoBuch[dfDicoBuch['Sampa']=='?']

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette,Sampa,Ipa
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus,?,?
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft,?,?
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance,?,?
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon,?,?
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned,?,?
...,...,...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography,?,?
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes,?,?
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric,?,?
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist,?,?
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica,?,?

In [18]:
dfDicoBuch[dfDicoBuch['Sampa']!='?']

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette,Sampa,Ipa
66,2,ăbyʹſs,G.,NaN,NaN,n.,32.0,20,abyss,@ b I s,əbɪs
120,2,ăcquĭʹt,F.,NaN,NaN,v.,14.0,21,acquit,@ k w I t,əkwɪt
161,3,ădhēʹrĕnce,L.,NaN,NaN,n.,55.0,21,adherence,@ d h I r\ @ n s,ədhɪɹəns
423,4,amēʹnĭty,L.,NaN,NaN,n.,29.0,25,amenity,@ m E n @ 4 i:,əmɛnəɾiː
514,5,ănĭmŏʹſity,L.,NaN,NaN,n.,48.0,26,animosity,{ n @ m A s @ 4 i:,ænəmɑsəɾiː
...,...,...,...,...,...,...,...,...,...,...,...
14337,3,vāʹgăbŏnd,L.,NaN,NaN,n.,8.0,221,vagabond,v { g @ b A n d,vægəbɑnd
14517,4,vībrāʹtion,L.,NaN,NaN,n.,47.0,223,vibration,v aI b r\ eI S @ n,v?bɹ?ʃən
14681,2,ŭnbăʹr,NaN,NaN,NaN,v.,67.0,225,unbar,@ n b A r\,ənbɑɹ
14794,3,ŭndĕrbĭd,NaN,nbSyll>1 et pas d'accent tonic,NaN,v.,36.0,227,underbid,V n d 3:r b I d,ʌndɜ:rbɪd
14900,3,ŭnglūʹed,NaN,NaN,NaN,a.,70.0,228,unglued,@ n g l u d,ənglud

In [19]:
dfDicoBuch.to_csv("./../data/dataframe/dfDicoBuch2.csv",index=False)

Seulement 77 mots ont trouvé une correspondance en Ipa et Sampa.  un dictionnaire composé de uniquement 1000 lignes Soit un sample du dictionnaire de Bigi ne pourrais l'ensemble des   15800 mots. Deplus dans les 1000 mots, il ne peuvent pas forcément être dans les 15800 mots du dictionnaire enrichis de Buch.  voici donc pourquoi on as 77 mots. 

Une façon de réparer le problème est  de prendre l'intégralité du dictionnaire de Bigi plutôt que 1000 mots afin d'avoir l'ensemble des pronétique Ipa et Sampa en plus de ceux de Buch  

on prendra donc par la suite l'ancienne version du Dictionnaire de Buch pour la suite du projet

In [20]:
dfDicoBuch = pd.read_csv("./../data/dataframe/dfDicoBuch.csv" , delimiter=",", encoding="utf8")
dfDicoBuch

,nbSyll,pron,origin,warning,remarques,POS,lineId,pageId,motVedette
0,3,aʹbăcus,NaN,NaN,NaN,n.,2.0,19,abacus
1,2,ăbăʹft,NaN,NaN,NaN,p.,3.0,19,abaft
2,3,ăbaiʹſănce,F.,NaN,NaN,n.,4.0,19,abaisance
3,3,ābăʹndon,F.,NaN,NaN,v.,5.0,19,abandon
4,4,ābăʹndŏned,NaN,NaN,NaN,a.,6.0,19,abandoned
...,...,...,...,...,...,...,...,...,...
15795,4,zōŏʹgrăphy,G.,NaN,NaN,n.,19.0,241,zoography
15796,4,zōŏʹphytès,G.,NaN,NaN,n.,20.0,241,zoophytes
15797,4,zōŏʹphŏric,G.,NaN,NaN,n.,21.0,241,zoophoric
15798,4,zōŏʹtŏmiſt,G.,NaN,NaN,n.,22.0,241,zootomist
15799,3,zŏʹtĭcā,G.,NaN,NaN,n.,23.0,241,zotica